
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: unya
  password: <%= ENV['SS_DATABASE_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: ss_development

test:
  <<: *default
  database: ss_test

production:
  <<: *default
  database: main
  username: main
  password: <%= ENV['SS_DATABASE_PASSWORD'] %>
